-- PostgreSQL Schema Dump from Supabase

-- Table structure for profiles
CREATE TABLE IF NOT EXISTS public."profiles" (
    "id" TEXT,
    "employee_id" TEXT,
    "first_name" TEXT,
    "last_name" TEXT,
    "job_title" TEXT,
    "department" TEXT,
    "role" TEXT,
    "employment_type" TEXT,
    "function" TEXT,
    "sub_function" TEXT,
    "manager_id" TEXT,
    "created_at" TEXT,
    "auth_email" TEXT,
    "USERID" TEXT,
    "STATUS" TEXT,
    "User Name" TEXT,
    "First Name" TEXT,
    "Nick" TEXT,
    "Middle Name" TEXT,
    "Last Name" TEXT,
    "Suffix" TEXT,
    "Job Title" TEXT,
    "Gender" TEXT,
    "Email" TEXT,
    "Manager" TEXT,
    "Human Resource" TEXT,
    "Department" TEXT,
    "Job Code" TEXT,
    "Division" TEXT,
    "Location" TEXT,
    "Time Zone" TEXT,
    "Date of Join" TEXT,
    "Bussiness Phone" TEXT,
    "Bussiness Fax" TEXT,
    "Address Line 1" TEXT,
    "Address Line 2" TEXT,
    "City" TEXT,
    "State" TEXT,
    "Zip" TEXT,
    "Country" TEXT,
    "Matrix Manager" TEXT,
    "Default Locale" TEXT,
    "Proxy" TEXT,
    "Seating Chart" TEXT,
    "Review Frequency" TEXT,
    "Last Review Date" TEXT,
    "Company Exit Date" TEXT,
    "Date of Birth" TEXT,
    "Auto Launch PMGM Criteria" TEXT,
    "phoneInfo-Personal" TEXT,
    "Other Role" TEXT,
    "Company" TEXT,
    "Cost Center" TEXT,
    "Business Unit" TEXT,
    "Entity" TEXT,
    "Section" TEXT,
    "Sub-Section" TEXT,
    "EmailInfo-Personal" TEXT,
    "Person-id-external" TEXT,
    "PhoneInfo-Business" TEXT,
    "EmailInfo-Business" TEXT,
    "Login Method" TEXT,
    "Assignment ID" TEXT,
    "Assignment UUID" TEXT,
    "Display Name" TEXT
);

-- Data for profiles
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('00000000-0000-0000-0000-000000000001', 'EMP001', 'Alexander', 'Vance', 'Head of Department', 'Corporate', 'hod', 'PERMANENT', 'Engineering', NULL, NULL, '2026-04-30T13:52:20.007257+00:00', 'alexgender@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('526cfc04-e8d3-4100-b7d4-c4b155711d0e', 'EMP020', 'Sarah', 'Jenkins', 'HR BP', 'HR', 'hr', 'PERMANENT', 'Human Resources', NULL, '00000000-0000-0000-0000-000000000001', '2026-04-30T13:52:20.007257+00:00', 'sarahjenkins@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('d414745f-8457-49d4-88e8-e5c6d605ed10', 'EMP015', 'Paul', 'Rudd', 'Fullstack Dev', 'Engineering', 'employee', 'PERMANENT', 'Engineering', NULL, '00000000-0000-0000-0000-000000000004', '2026-04-30T13:52:20.007257+00:00', 'paulrudd@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('e5c0e479-0723-41bc-944a-3001e0556aaf', 'EMP017', 'Idris', 'Elba', 'Cloud Lead', 'Engineering', 'employee', 'PERMANENT', 'Engineering', NULL, '00000000-0000-0000-0000-000000000004', '2026-04-30T13:52:20.007257+00:00', 'idriselba@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('00000000-0000-0000-0000-000000000002', 'EMP002', 'Sarah', 'Chen', 'Engineering Manager', 'Core Dev', 'manager', 'PERMANENT', 'Engineering', NULL, '526cfc04-e8d3-4100-b7d4-c4b155711d0e', '2026-04-30T13:52:20.007257+00:00', 'sarah.chen@company.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('e7228f73-f4bd-4007-a664-be87487ee842', 'EMP007', 'Tom', 'Hanks', 'Senior Designer', 'Product', 'employee', 'PERMANENT', 'Product', NULL, '00000000-0000-0000-0000-000000000004', '2026-04-30T13:52:20.007257+00:00', 'tomhanks@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('ea2b486a-7f35-4673-a6b3-6d9f2885c77b', 'EMP012', 'Oscar', 'Wilde', 'Ops Executive', 'Ops', 'employee', 'PERMANENT', 'Operations', NULL, '00000000-0000-0000-0000-000000000004', '2026-04-30T13:52:20.007257+00:00', 'oscarwilde@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('f4590e94-7e56-4a6d-b0c3-17892a57694c', 'EMP016', 'Tessa', 'Thompson', 'DBA', 'Engineering', 'employee', 'PERMANENT', 'Engineering', NULL, '00000000-0000-0000-0000-000000000001', '2026-04-30T13:52:20.007257+00:00', 'tessathompson@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('f76ed73b-19b7-46a8-bc42-14b28e931cdc', 'EMP011', 'Nina', 'Simone', 'Analyst', 'Product', 'employee', 'PERMANENT', 'Product', NULL, '00000000-0000-0000-0000-000000000003', '2026-04-30T13:52:20.007257+00:00', 'ninasimone@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('00000000-0000-0000-0000-000000000006', 'EMP006', 'Julia', 'Soto', 'Senior Dev', NULL, 'employee', 'PERMANENT', 'Engineering', NULL, '00000000-0000-0000-0000-000000000002', '2026-04-30T13:52:20.007257+00:00', 'juliosoto@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('00000000-0000-0000-0000-000000000003', 'EMP003', 'Marcus', 'Reed', 'Product Lead', 'Product', 'manager', 'PERMANENT', 'Product', NULL, '526cfc04-e8d3-4100-b7d4-c4b155711d0e', '2026-04-30T13:52:20.007257+00:00', 'marcusreed@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('00000000-0000-0000-0000-000000000004', 'EMP004', 'Elena', 'Rossi', 'Ops Director', 'Ops', 'manager', 'PERMANENT', 'Operations', NULL, '526cfc04-e8d3-4100-b7d4-c4b155711d0e', '2026-04-30T13:52:20.007257+00:00', 'elenarossie@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('00000000-0000-0000-0000-000000000005', 'EMP005', 'David', 'Kim', 'Tech Lead', NULL, 'manager', 'PERMANENT', 'Engineering', NULL, '00000000-0000-0000-0000-000000000001', '2026-04-30T13:52:20.007257+00:00', 'davidkim@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('0d2de698-a2a1-4830-a74a-6195928e82de', 'EMP014', 'Zoe', 'Kravitz', 'UI Eng', 'Engineering', 'employee', 'PERMANENT', 'Engineering', NULL, '00000000-0000-0000-0000-000000000002', '2026-04-30T13:52:20.007257+00:00', 'zoekravit@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('1d52493e-5ba4-42f3-b7bc-70e86ef49a98', 'EMP008', 'Leo', 'Miller', 'Backend Dev', 'Engineering', 'employee', 'PERMANENT', 'Engineering', NULL, '00000000-0000-0000-0000-000000000002', '2026-04-30T13:52:20.007257+00:00', 'leomiller@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('262a27f1-2cdc-4971-a714-56c73bbfa41d', 'EMP019', 'Will', 'Smith', 'Security Eng', 'Engineering', 'employee', 'PERMANENT', 'Engineering', NULL, '00000000-0000-0000-0000-000000000002', '2026-04-30T13:52:20.007257+00:00', 'willsmith@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('2fb0e02b-30de-482d-9f4f-5b586b1c9366', 'EMP013', 'Maya', 'Angelou', 'Ops Support', 'Ops', 'employee', 'PROBATION', 'Operations', NULL, '00000000-0000-0000-0000-000000000003', '2026-04-30T13:52:20.007257+00:00', 'maya@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('32b295f4-3c6c-4b8b-90d6-59237662500e', 'EMP018', 'Gal', 'Gadot', 'Data Sci', 'Engineering', 'employee', 'PERMANENT', 'Engineering', NULL, '00000000-0000-0000-0000-000000000003', '2026-04-30T13:52:20.007257+00:00', 'galgadot@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('668d00c6-b6fb-4c8f-b546-7be5e98c56da', 'EMP009', 'Anna', 'White', 'Junior Dev', 'Engineering', 'employee', 'PROBATION', 'Engineering', NULL, '00000000-0000-0000-0000-000000000003', '2026-04-30T13:52:20.007257+00:00', 'annawhite@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public."profiles" ("id", "employee_id", "first_name", "last_name", "job_title", "department", "role", "employment_type", "function", "sub_function", "manager_id", "created_at", "auth_email", "USERID", "STATUS", "User Name", "First Name", "Nick", "Middle Name", "Last Name", "Suffix", "Job Title", "Gender", "Email", "Manager", "Human Resource", "Department", "Job Code", "Division", "Location", "Time Zone", "Date of Join", "Bussiness Phone", "Bussiness Fax", "Address Line 1", "Address Line 2", "City", "State", "Zip", "Country", "Matrix Manager", "Default Locale", "Proxy", "Seating Chart", "Review Frequency", "Last Review Date", "Company Exit Date", "Date of Birth", "Auto Launch PMGM Criteria", "phoneInfo-Personal", "Other Role", "Company", "Cost Center", "Business Unit", "Entity", "Section", "Sub-Section", "EmailInfo-Personal", "Person-id-external", "PhoneInfo-Business", "EmailInfo-Business", "Login Method", "Assignment ID", "Assignment UUID", "Display Name") VALUES ('97af2045-8c9d-4ef7-9ccf-40c7f3786dfd', 'EMP010', 'Chris', 'Evans', 'QA Specialist', 'Engineering', 'employee', 'PERMANENT', 'Engineering', NULL, '00000000-0000-0000-0000-000000000003', '2026-04-30T13:52:20.007257+00:00', 'chrisevans@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- Table structure for monthly_reviews
CREATE TABLE IF NOT EXISTS public."monthly_reviews" (
    "id" TEXT,
    "employee_id" TEXT,
    "manager_id" TEXT,
    "cycle_id" TEXT,
    "overall_result" TEXT,
    "rating_status" TEXT,
    "manager_comment" TEXT,
    "emp_achievements" TEXT,
    "emp_blockers" TEXT,
    "emp_learning" TEXT,
    "emp_proof_points" TEXT,
    "submitted_at" TEXT,
    "attachments" TEXT
);

-- Data for monthly_reviews
INSERT INTO public."monthly_reviews" ("id", "employee_id", "manager_id", "cycle_id", "overall_result", "rating_status", "manager_comment", "emp_achievements", "emp_blockers", "emp_learning", "emp_proof_points", "submitted_at", "attachments") VALUES ('cbfb50fc-1143-4b71-93f9-f1d8f71bf1f4', '526cfc04-e8d3-4100-b7d4-c4b155711d0e', '00000000-0000-0000-0000-000000000001', 'ffffffff-ffff-ffff-ffff-ffffffffffff', 'YES', 'APPROVED', 'I need updated for quarter 4', 'testing', 'testing', 'testing', 'testing', '2026-05-01T12:52:15.292+00:00', '[{"url":"https://zkvkuxyggdlsrtkqechs.supabase.co/storage/v1/object/public/evidence/526cfc04-e8d3-4100-b7d4-c4b155711d0e_1777615370778.xlsx","name":"Login Details and Website URL.xlsx","path":"526cfc04-e8d3-4100-b7d4-c4b155711d0e_1777615370778.xlsx"}]');
INSERT INTO public."monthly_reviews" ("id", "employee_id", "manager_id", "cycle_id", "overall_result", "rating_status", "manager_comment", "emp_achievements", "emp_blockers", "emp_learning", "emp_proof_points", "submitted_at", "attachments") VALUES ('3281988b-e682-42aa-a46b-84c09d91050c', 'e7228f73-f4bd-4007-a664-be87487ee842', '00000000-0000-0000-0000-000000000004', 'ffffffff-ffff-ffff-ffff-ffffffffffff', 'YES', 'APPROVED', 'performance is good', 'testing', 'testing', 'testing', 'testing', '2026-05-01T13:02:26.285+00:00', '[{"url":"https://zkvkuxyggdlsrtkqechs.supabase.co/storage/v1/object/public/evidence/e7228f73-f4bd-4007-a664-be87487ee842_1777640466493.csv","name":"profiles_rows (5).csv","path":"e7228f73-f4bd-4007-a664-be87487ee842_1777640466493.csv"}]');
INSERT INTO public."monthly_reviews" ("id", "employee_id", "manager_id", "cycle_id", "overall_result", "rating_status", "manager_comment", "emp_achievements", "emp_blockers", "emp_learning", "emp_proof_points", "submitted_at", "attachments") VALUES ('d46d7134-5a46-4b8d-af0e-7b3aa73499db', '0d2de698-a2a1-4830-a74a-6195928e82de', '00000000-0000-0000-0000-000000000002', 'ffffffff-ffff-ffff-ffff-ffffffffffff', NULL, 'REJECTED', 'details are missing', '', '', '', '', NULL, '[]');
INSERT INTO public."monthly_reviews" ("id", "employee_id", "manager_id", "cycle_id", "overall_result", "rating_status", "manager_comment", "emp_achievements", "emp_blockers", "emp_learning", "emp_proof_points", "submitted_at", "attachments") VALUES ('39906a23-f62e-41d7-834d-bee885eaf93d', '00000000-0000-0000-0000-000000000006', '00000000-0000-0000-0000-000000000002', 'ffffffff-ffff-ffff-ffff-ffffffffffff', NULL, 'PENDING', NULL, 'work done sucessfully', 'all the bugs solved and verified', 'workflows have assigned', 'iahve attached the evidence', NULL, '[{"url":"https://zkvkuxyggdlsrtkqechs.supabase.co/storage/v1/object/public/evidence/00000000-0000-0000-0000-000000000006_1777619882064.csv","name":"main_themes_rows.csv","path":"00000000-0000-0000-0000-000000000006_1777619882064.csv"}]');
INSERT INTO public."monthly_reviews" ("id", "employee_id", "manager_id", "cycle_id", "overall_result", "rating_status", "manager_comment", "emp_achievements", "emp_blockers", "emp_learning", "emp_proof_points", "submitted_at", "attachments") VALUES ('9f985cb5-504e-4b8b-a081-d2bd4fd6911d', '00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', 'ffffffff-ffff-ffff-ffff-ffffffffffff', NULL, 'PENDING', NULL, 'Enhanced all the Bugs and cleared', 'JWT Authentication issue occured as challenges and solved using twilo', '', 'i am attaching the screenshots as evidences ', NULL, '[{"url":"https://zkvkuxyggdlsrtkqechs.supabase.co/storage/v1/object/public/evidence/00000000-0000-0000-0000-000000000001_1777635913547.csv","name":"profiles_rows (4).csv","path":"00000000-0000-0000-0000-000000000001_1777635913547.csv"}]');
INSERT INTO public."monthly_reviews" ("id", "employee_id", "manager_id", "cycle_id", "overall_result", "rating_status", "manager_comment", "emp_achievements", "emp_blockers", "emp_learning", "emp_proof_points", "submitted_at", "attachments") VALUES ('1c810749-3639-4891-94f7-9ddc0bd33168', '00000000-0000-0000-0000-000000000003', '526cfc04-e8d3-4100-b7d4-c4b155711d0e', 'ffffffff-ffff-ffff-ffff-ffffffffffff', NULL, 'PENDING', NULL, 'UI/UX changes have sucessfully implemented ', 'challenge faced at creating a bot ui in the profile box', 'fprevious we used low light ui now upgraded to premium arabic style ui', 'attached the photos as references', NULL, '[{"url":"https://zkvkuxyggdlsrtkqechs.supabase.co/storage/v1/object/public/evidence/00000000-0000-0000-0000-000000000003_1777637922137.csv","name":"profiles_rows (6).csv","path":"00000000-0000-0000-0000-000000000003_1777637922137.csv"}]');
INSERT INTO public."monthly_reviews" ("id", "employee_id", "manager_id", "cycle_id", "overall_result", "rating_status", "manager_comment", "emp_achievements", "emp_blockers", "emp_learning", "emp_proof_points", "submitted_at", "attachments") VALUES ('51b3a8c7-f62c-47ac-8608-2d725037e064', 'f4590e94-7e56-4a6d-b0c3-17892a57694c', '00000000-0000-0000-0000-000000000001', 'ffffffff-ffff-ffff-ffff-ffffffffffff', 'YES', 'APPROVED', 'very good ', 'test', 'test', 'test', 'test', '2026-05-01T12:51:42.728+00:00', '[{"url":"https://zkvkuxyggdlsrtkqechs.supabase.co/storage/v1/object/public/evidence/f4590e94-7e56-4a6d-b0c3-17892a57694c_1777638898956.csv","name":"profiles_rows (6).csv","path":"f4590e94-7e56-4a6d-b0c3-17892a57694c_1777638898956.csv"}]');

