services:
  backend-api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - MIGRATIONS_PATH=/app/database/migrations
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile # Your existing root Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend-api
    restart: always