-- ============================================================
-- MIGRATION 003: Initial Seed Data
-- Date: 2026-05-06
-- ============================================================


-- Admin profile 
INSERT INTO profiles (
    id,
    employee_id,
    first_name,
    last_name,
    job_title,
    department,
    role,
    employment_type,
    "function",
    sub_function,
    manager_id,
    auth_email,
    is_active,
    "USERID",
    "STATUS",
    "User Name", 
    "First Name", 
    "Nick", 
    "Middle Name", 
    "Last Name", 
    "Suffix", 
    "Job Title", 
    "Gender", 
    "Email", 
    "Manager", 
    "Human Resource", 
    "Department", 
    "Job Code", 
    "Division", 
    "Location", 
    "Time Zone", 
    "Date of Join", 
    "Bussiness Phone", 
    "Bussiness Fax", 
    "Address Line 1", 
    "Address Line 2", 
    "City", 
    "State", 
    "Zip", 
    "Country", 
    "Matrix Manager", 
    "Default Locale", 
    "Proxy", 
    "Seating Chart", 
    "Review Frequency", 
    "Last Review Date", 
    "Company Exit Date", 
    "Date of Birth", 
    "Auto Launch PMGM Criteria", 
    "phoneInfo-Personal", 
    "Other Role", 
    "Company", 
    "Cost Center", 
    "Business Unit", 
    "Entity", 
    "Section", 
    "Sub-Section", 
    "EmailInfo-Personal", 
    "Person-id-external", 
    "PhoneInfo-Business", 
    "EmailInfo-Business", 
    "Login Method", 
    "Assignment ID", 
    "Assignment UUID", 
    "Display Name"

)
VALUES (
    '00000000-0000-0000-0000-000000000001', 
    'EMP001',                               
    'Alexander',                            
    'Vance',                                
    'Head of Department',                   
    'Corporate',                            
    'hod',                                  
    'PERMANENT',                            
    'Engineering',                          
    NULL,                                  
    NULL,                                   
    'alexgender@gmail.com',                 
    true,        
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
)
ON CONFLICT (id) DO NOTHING;

